name: CI/CD Pipeline for Project

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'  # You can adjust the Java version as needed

      - name: Set up Maven
        run: |
          wget -q https://downloads.apache.org/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz
          tar xf apache-maven-3.8.3-bin.tar.gz
          export PATH=$PATH:$(pwd)/apache-maven-3.8.3/bin
          mvn --version

      - name: Build with Maven
        run: mvn clean install  # Modify this command according to your Maven goals
